dist: bionic
language: python
python:
  - "3.7"

#matrix:
#  include:
#    - name: "Python 3.7 on Windows"
#      os: windows
#      language: shell
#      before_install: choco install python
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install .[test]

script: pytest tests/
